server:
  port: 8888  
spring:
 cloud:
  stream:
   kafka:
    binder:
     brokers: localhost:9092
   bindings:
    messages-in:
     destination: CreateCustomer
     contentType: application/json
    messages-out:
     destination: CreateCustomer
     contentType: application/json
        